name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master
      - homolog
      - dev
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente para deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - homolog
          - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        run: |
          cd frontend
          npm ci

      - name: Build
        run: |
          cd frontend
          CI=false npm run build
          echo "Verificando diretório build..."
          ls -la build
          if [ ! -d "build" ]; then
            echo "Erro: Diretório build não encontrado"
            exit 1
          fi
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_ENV: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || github.ref_name }}

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: react

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages

      - name: Show Deployment URLs
        run: |
          echo "Ambiente de Desenvolvimento: https://jistriane.github.io/Ibelieve-Finance/dev"
          echo "Ambiente de Homologação: https://jistriane.github.io/Ibelieve-Finance/homolog"
          echo "Ambiente de Produção: https://jistriane.github.io/Ibelieve-Finance/prod"
          echo "URL do Deploy Atual: ${{ steps.deployment.outputs.page_url }}" 